### ISSUE TITLE
Graveyard Improvements

### ISSUE THREAD

**Issue by walrii** [arbrown/pao#38]
I've been thinking about redoing the dead pieces.

Here are some use cases, things I've sometimes tried to compute, or think others might want
- I want to know which pieces are dead (current dead pieces)
- I want to know which pieces are still face down (can be mentally computed from board and current dead pieces)
- I want to what pieces are not dead (inverse of dead pieces)
- New players want to be reminded of the piece ranking
- New players sometimes want to be reminded of the logograms
- New players want compare the logograms of red vs black

My conclusions
- For new players, all the pieces, up, down, and dead need to be represented, in order
- It should be easy to tell, which pieces are down, up, and dead from their appearance

Ideas
- The dead pieces should stand out, or be the most obvious
- The up and down pieces should be dimmer, 
- Down pieces should be green, or have a green cast to them, or a green circle
- Perhaps dead pieces could have an X or slashed circle or headstone superimposed, but not enough to obsure the logogram
- A hover should identify eash piece and its status

**Comment by arbrown** [comment]
I think this is a reasonable update.  I added tooltips for pieces on the board in b33cee6c73e8d6724cdd9c246499fccb3c52ff22, so that will help people recognize the pieces in an unfamiliar font for now.

I recently started playing a new banqi game on my iPhone, and it uses a similar system:

![image](https://user-images.githubusercontent.com/498727/82680648-d0351580-9c09-11ea-8f58-a8b749625a0b.png)

* All pieces are shown on the sides
* Up pieces look like smaller versions of the piece
* Down pieces have a green tint over them
* Dead pieces have a dark/black tint
* The last killed piece has a different color background for one turn (this is where I got the idea for the similar system I implemented in b33cee6c73e8d6724cdd9c246499fccb3c52ff22.)

I think all the styling could be done in CSS, and theoretically everything could be computed  based on the information currently being sent back by the server (list of all dead pieces.)  I think this would be best implemented as a new React component to replace [Dead.jsx](https://github.com/arbrown/pao/blob/master/client/jsx/Dead.jsx).
